config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'schedule' => 'static_pages#schedule'
  get 'temp_schedule' => 'static_pages#schedule_temp'
  get 'team' => 'static_pages#team'
  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'volunteer' => 'static_pages#donation' #backward compatible for path change
  get 'donation' => 'static_pages#donation'
  get 'coc' => 'static_pages#code_of_conduct'
  get 'ping' => 'static_pages#ping'
  get 'contact' => 'contact_us#new'
  get 'amazon' => 'static_pages#amazon'

  post 'contact' => 'contact_us#create'

  get 'register' => 'users#new'
  resources :users

end

app/views/newsletters/2015/05/_newsletter_15.html.erb
<B>May 15 2015</B>
<H3><I>Summer 2015 schedule is now available</I></H3>

Registration will be open until Wednesday, <span class="bold">May 13th</span>.  All Assessment Tests and Student Agreement forms need to be submitted by <span class="bold">Friday, May 15th</span>.
<p></p>
<span class="bold underline">To all new students</span>: Please take a look at our <%= link_to "FAQ", faq_path %> page for instructions on installing <%= link_to "ZOOM", ApplicationHelper::ZOOM_URL %> to attend classes.  Also, all classes are scheduled in <span class="bold">Pacific Time Zone</span>.
<p></p>
<span class="bold underline">To all parents</span>: We need your partnerships to make this a successful experience for your children.
April, 2015 registration is now closed.  You should have received a confirmation email from us along with your instructor's Zoom id.  If you have not, please contact us.