config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'schedule' => 'static_pages#schedule'
  get 'temp_schedule' => 'static_pages#schedule_temp'
  get 'team' => 'static_pages#team'
  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'volunteer' => 'static_pages#donation' #backward compatible for path change
  get 'donation' => 'static_pages#donation'
  get 'coc' => 'static_pages#code_of_conduct'
  get 'ping' => 'static_pages#ping'
  get 'contact' => 'contact_us#new'
  get 'amazon' => 'static_pages#amazon'

  post 'contact' => 'contact_us#create'

  get 'register' => 'users#new'
  resources :users

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def schedule
  end

  def team
  end

  def faq
  end

  def about
  end

  def ping
    render :text => 'pong'
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>


<H1><i class="fa fa-info-circle"></i> About Us</H1>
<div id="about">

  <div class="title">
    Who We Are:
  </div>
  <div class="description">
    Pay It Forward For Education, Inc. is a nonprofit organization established on September, 2014 under the Internal
    Revenue Code (IRC) Section 501 (c) (3).
  </div>
  <div class="description">
    Through the use of modern technology, we are introducing online education to students from Elementary through High
    School. We offer Education Services, namely, providing online interactive tutoring services for students in the
    field of Mathematics, Language Arts and Computer Science.
  </div>
  <div class="title">
    Our Philosophy
  </div>
  <div class="description">Pay It Forward For Education (PIFFE) was created through the love and passion that our
    instructors have for education and technology. You can say that PIFFE has the best of both worlds!
  </div>
  <div class="description">Deeply grateful for the blessings in their own lives, PIFFE instructors want to pay it
    forward by donating their time and talents to inspire students to do their best. We strive to help students relate
    what they learn in class to actual applications in their own life. We empower our students to think outside the box,
    to articulate their thought process among their peers, and to have the courage to question, or even challenge what
    they are taught. In this way, our students are able to build confidence in their academic aptitudes and also their
    public speaking skills.
  </div>
  <div class="description">Most importantly, we wish to instill within our students a deep appreciation for knowledge
    and compassion. We hope our students in turn, will pay it forward by proliferating the sharing of knowledge among
    their own circle of connections. Just imagine the impact we can achieve when students reach out to share knowledge
    among their friends, and those friends in turn, reach out to help their own friends!
  </div>
  <div class="description">
    PIFFE team members believe in the power of knowledge sharing. Together, we can create a great ripple effect of
    compassionate individuals inspired to pay it forward to make this world a better place!
  </div>

  <div class="title">
    Cost
  </div>
  <div class="description">
    There is NO COST to attend the sessions.
  </div>
  <div class="title">
    Registration
  </div>
  <div class="description">
    Students need to sign up to attend sessions. Please see our <%= link_to "Schedule", schedule_path %> for more
    details.
  </div>
  <div class="title">
    What we offer
  </div>
  <div class="description">
    <ul>
      <li>FREE online interactive Math, Language Arts and Computer Science tutoring</li>
      <li>A program that is accessible for students everywhere - from home or on the road through desktop, mobile and
        tablet devices
      </li>
      <li>30 - 45 minutes per session</li>
      <li>Maximum of 5 students per class</li>
    </ul>
  </div>

</div>

app/views/static_pages/amazon.html.erb
<% provide(:title, "Amazon") %>

<div id="amazon">
  <H2><%= image_tag("amazon/amazon_logo.png",  class:"logo-style", :size => "50") %> How Your Amazon Purchases Can Support PIFFE</H2>

  <%= render 'static_pages/amazon' %>

</div>

app/views/static_pages/code_of_conduct.html.erb
<% provide(:title, "Code of Conduct") %>


<div id="coc-news-well" class="well news-well">
    <H2><i class="fa fa-university"></i> PIFFE Code of Conduct</H2>

    <div class="blank-line"></div>
    <div class="blank-line"></div>
    <div class="row", id="coc">

      <div class="col-md-10 col-md-offset-1 announcement-text">
        <ol>
          <li>During the sessions, students are expected to treat the instructor and their peers with RESPECT</li>
          <li>Each student is expected to log on and be ready for class on time</li>
          <li> Camera/webcam should NOT be on during the sessions</li>
          <li>All phone/computer speakers should be set to MUTE unless called on to participate by the instructor</li>
        </ol>
        </div>
      </div>
</div>

app/views/static_pages/coming_soon.html.erb
<% provide(:title, "ComingSoon") %>
<H1>Coming Soon</H1>

app/views/static_pages/donation.html.erb
<% provide(:title, "Donation") %>

<div id="volunteer">
<H2><i class="fa fa-group"></i> Get Involved</H2>
  <br>
  <div id="image-row">
    <div>
      <%= image_tag("misc/book-shelves.jpg", height: '96', width: '128') %>
    </div>
    <div>
      <%= image_tag("misc/math-blackboard.jpg", height: '96', width: '128') %>
    </div>
    <div>
      <%= image_tag("misc/notebook-and-pencil.jpg", height: '96', width: '128') %>
    </div>
  </div>

  You can help our organization better serve students across the nation by donating your Time, Talents or Financial Contributions.
  <br><br>

  <div class="title">
    Be a Volunteer
  </div>
  <div>
    We are seeking dedicated volunteers who are passionate about teaching with tutoring experience in the subjects of
    Math, Language Arts and Computer Science.  By donating an hour a week of your time as a tutor, you have the
    opportunity to engage our students, motivate them, and help them to improve and excel in their studies.
    <br><br>
    We are also looking for dedicated software developers to help build our web-based teaching platform.  As part of our
    software development team, you have the opportunity to develop core features of our teaching platform, one that will
    enable the organization to build the best teaching curriculum for our students.
    <br><br>
    Please contact us at <b>volunteering@payitforward4edu.com</b> for more information.
    <br><br>
  </div>

  <div class="title">
    Make a Donation
  </div>
  <div>
    Already have a busy schedule, but would still love to support our mission? Your financial contributions will allow
    us to continue offering the best tutoring services to our students.
    <br><br>
    You can make the donation through PayPal at <b>donation@payitforward4edu.com</b>.
    <br><br>
  </div>


  <div class="title">
    Shop at Amazon
  </div>
  <%= render 'static_pages/amazon' %>


  <br>
  <br>
</div>

app/views/static_pages/faq.html.erb
<% provide(:title, "FAQ") %>



<H1><i class="fa fa-lightbulb-o"></i> Frequently Asked Questions</H1>
<div id="faqs">
  <div class="question">How do I register?</div>
  <div class="answer">To register for sessions, please check on <%= link_to "schedule", schedule_path %> for more details</div>

  <div class="question">How do I attend sessions?</div>
  <div class="answer">
    All sessions are held live using Zoom <p></p>
    Please make sure Zoom is installed before class starts <p></p>
    <ul>
      <li>Go <%= link_to "here", ApplicationHelper::ZOOM_URL %> to install Zoom</li>
      <li>Enter meeting ID (meeting ID is provided once registered)</li>
      <li>(Optional) Join from dial-in phone line if you don't have speakers. Dial: +1(415)762-9988 or +1(646)568-7788</li>
      <li>Participant ID: Shown after joining the meeting</li>
      <li>Enter only first name</li>
      <li>Disable camera; otherwise, you will be disconnected from session</li>
    </ul>
  </div>

  <div class="question">What subjects are available?</div>
  <div class="answer">Mathematics, Language Arts and Computer Science</div>

  <div class="question">What grade level pertains to these sessions?</div>
  <div class="answer">Elementary through High School</div>

  <div class="question">What are expected from students in a session?</div>
  <div class="answer">We do expect the students to follow <%= link_to "PIFFE Code of Conduct", coc_path %></div>

  <div class="question">For additional questions, please <%= link_to "contact us", contact_path %>.</div>
  <div class="answer"></div>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<script type="text/javascript">
  window.location.href="https://www.piffe.org"  // put your correct path in a string here
</script>

<div id="home">
  <div class="blank-line"></div>

  <!-- 16:9 aspect ratio -->
  <div class="spand12 center">
    <iframe width="640" height="390" src="https://www.youtube.com/embed/bek6Q5gM07Q" allowfullscreen></iframe>

  </div>

  <div class="blank-line"></div>
    <div class="slogan text-center">
      <span class="slogan-1">For Future</span>
      <span class="slogan-2">- For Kids - </span>
      <span class="slogan-3">For Free</span>
    </div>

  <div class="blank-line"></div>
  <div class="blank-line"></div>

  <div id="home-announcement" class="media" >
    <div class="media-left">
      <%= link_to image_tag("piffe_logo.png", alt: "PIFFE logo", width: "250", class: "logo-style"), root_path %>
      <%= link_to image_tag("amazon/amazon_smile.png", width: "250", class: "logo-style"), amazon_path %>

    </div>
    <div class="media-body well">
      <div class="media-heading">
        Newsletters
      </div>
      <p></p>
      <div class="announcement-text">
        <%= render 'newsletters/newsletter' %>

      </div>
    </div>
  </div>

  <div class="blank-line"></div>
  <div class="blank-line"></div>
  <div id="important-note" class="alert alert-info">

    <div class="row">
      <div class="col-md-10 col-md-offset-1 important-note-text">
        <strong>Important Note:</strong> We are <strong>NOT</strong> associated with the other Pay It Forward For Education (www.payitforward4edu.org)
        based in Chicago, Illinois regarding student loan debt.
      </div>
    </div>
  </div>
  <!--
  <div class="spand12 center">
    <div class="slogan text-center">
      <span class="slogan-1">Student Testimonials</span>
    </div>
    <iframe width="640" height="390" src="https://www.youtube.com/embed/qFw5U1fmIPE" allowfullscreen></iframe>

  </div>
  -->
  <div class="blank-line"></div>

</div>

app/views/static_pages/schedule.html.erb
<% provide(:title, "Schedule") %>

<div id="schedule-news-well" class="well news-well">
  <H2><i class="fa fa-calendar"></i> 2016-2017 schedule </H2>
  Registration is open for the 2016-2017 school year on 8/22. Our sessions are setup in a review format, designed to help
  students sharpen their existing skills and knowledge.

  <div class="blank-line"></div>
  <div><b>Math:</b> Registration will remain open throughout the school year until we reach the maximum of 5 students
    for any given class. Topics are grouped by grade level. However, students are free to attend sessions of their
    interest to review material they’ve already learned.
  </div>

  <div class="blank-line"></div>
  <div><strong>Registration:</strong> Send an email to administrator@payitforwardforedu.com with the attachment of the completed student agreement form below.
  </div>

  <div class="blank-line"></div>
  <div><b>Student Agreement:</b>Students must submit the Student Agreement by September 11th in order
    to receive a login id to attend the tutoring sessions. Click here to download
    the <%= link_to("Student Agreement", "/downloads/student_agreement.pdf", :target => "_blank") %>.
  </div>

  <div class="blank-line"></div>
  <div><b>Important date(s):</b></div>
  Classes start on the week of 9/12
  <br>
</div>


<div id="schedule-tab">
  <ul class="nav nav-tabs" role="tablist">
    <li class="active">
      <a href="#math" role="tab" data-toggle="tab">
        <icon class="fa fa-calculator"></icon>
        Mathematics
      </a>
    </li>
    <!-- li>
      <a href="#language" role="tab" data-toggle="tab">
        <i class="fa fa-book "></i> Language Arts
      </a>
    </li -->
  </ul>
</div>

<!-- Tab panes -->
<div id="schedule-tab-content" class="tab-content">

  <div role="tabpanel" class="tab-pane fade active in" id="math">

    <%= render 'classes/2016/fall/math/grade_4' %>
    <%= render 'classes/2016/fall/math/grade_5' %>
    <%= render 'classes/2016/fall/math/grade_6' %>
    <%= render 'classes/2016/fall/math/grade_7' %>
    <%= render 'classes/2016/fall/math/grade_8' %>
    <%= render 'classes/2016/fall/math/grade_9' %>
    <%= render 'classes/2016/fall/math/grade_10' %>
    <%= render 'classes/2016/fall/math/grade_11' %>
    <%= render 'classes/2016/fall/math/grade_12' %>
  </div>

</div>

app/views/static_pages/schedule_temp.html.erb
<% provide(:title, "Schedule") %>


<div id="schedule-news-well" class="well news-well">
  <H2><i class="fa fa-calendar"></i> Fall 2015 schedule </H2>
  Registration is now open for the Fall 2015 semester. Our sessions are setup in a review format, designed to help
  students sharpen their existing skills and knowledge.

  <div class="blank-line"></div>
  <div><b>Language Arts:</b> Registration will remain open until September 8th, 2015. We highly recommend that you
    register at your earliest convenience as we limit class size to 10 students per class.
  </div>

  <div class="blank-line"></div>
  <div><b>Math:</b> Registration will remain open throughout the semester until we reach the maximum of 10 students
    for any given class. Topics are grouped by grade level. However, students are free to attend sessions of their
    interest to review material they’ve already learned.
  </div>

  <div class="blank-line"></div>
  <div><b>Student Agreement:</b> All registered students must submit the Student Agreement by September 10th in order
    to receive a login id to attend the tutoring sessions. Click here to download
    the <%= link_to("Student Agreement", "/downloads/student_agreement.pdf", :target => "_blank") %>.
  </div>

</div>

<div id="schedule-tab">
  <ul class="nav nav-tabs" role="tablist">
    <li class="active">
      <a href="#math" role="tab" data-toggle="tab">
        <icon class="fa fa-calculator"></icon>
        Mathematics
      </a>
    </li>
    <li>
      <a href="#language" role="tab" data-toggle="tab">
        <i class="fa fa-book "></i> Language Arts
      </a>
    </li>
  </ul>
</div>

<!-- Tab panes -->
<div id="schedule-tab-content" class="tab-content">

  <div role="tabpanel" class="tab-pane fade active in" id="math">

    <%= render 'classes/2015/fall/math/grade_3' %>
    <%= render 'classes/2015/fall/math/grade_4' %>
    <%= render 'classes/2015/fall/math/grade_5' %>
    <%= render 'classes/2015/fall/math/grade_6' %>
    <%= render 'classes/2015/fall/math/grade_7' %>
    <%= render 'classes/2015/fall/math/grade_8' %>
    <%= render 'classes/2015/fall/math/alg_1' %>
  </div>

  <div role="tabpanel" class="tab-pane fade" id="language">
    <%= render 'classes/2015/fall/lang/grade_3' %>
    <%= render 'classes/2015/fall/lang/grade_4' %>
    <%= render 'classes/2015/fall/lang/grade_6' %>
    <%= render 'classes/2015/fall/lang/grade_8' %>
  </div>

</div>

app/views/static_pages/team.html.erb
<% provide(:title, "Meet our team") %>

<div class="well news-well">
  <H2><i class="fa fa-users"></i> Meet Our Team</H2>
  Our instructors are volunteers who want to help students everywhere to improve and excel in the subjects of Mathematics and Language Arts.
</div>

<%= render 'static_pages/instructors/alyssa_nguyen' %>
<%= render 'static_pages/instructors/daniella_romero' %>
<%= render 'static_pages/instructors/megan_pham' %>
<%= render 'static_pages/instructors/otto_leung' %>
<%= render 'static_pages/instructors/quynn_le' %>
<%= render 'static_pages/instructors/scott_daniel' %>
<%= render 'static_pages/instructors/regina_schekall' %>
<%= render 'static_pages/instructors/shakir_saud' %>
<%= render 'static_pages/instructors/shruthi_venkatesan' %>
<%= render 'static_pages/instructors/thinh_to' %>

<br><br>