config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'schedule' => 'static_pages#schedule'
  get 'temp_schedule' => 'static_pages#schedule_temp'
  get 'team' => 'static_pages#team'
  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'volunteer' => 'static_pages#donation' #backward compatible for path change
  get 'donation' => 'static_pages#donation'
  get 'coc' => 'static_pages#code_of_conduct'
  get 'ping' => 'static_pages#ping'
  get 'contact' => 'contact_us#new'
  get 'amazon' => 'static_pages#amazon'

  post 'contact' => 'contact_us#create'

  get 'register' => 'users#new'
  resources :users

end

app/views/classes/2015/summer/lang/_grade_3.html.erb
<div id="schedulePanel" class="panel panel-default my-lang-panel">
  <div class="panel-heading" role="tab" id="heading3rdGradeLang">
    <h4 class="panel-title">
      <a data-toggle="collapse"  href="#collapse3rdGradeLang" aria-expanded="true" aria-controls="collapse3rdGradeLang">
        3<sup>rd</sup> / 4<sup>th</sup> / 5<sup>th</sup> Grade <i class="fa fa-plus-circle"></i>
      </a>
    </h4>
  </div>
  <div id="collapse3rdGradeLang" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading3rdGradeLang">
    <div class="panel-body">
      <div><H4>Instructor: <%= link_to("David Trius", team_path + '#david-trius') %></H4></div>
      <div><H5>Day: Monday - Thursday</H5></div>
      <div><H5>Time: 6:35pm PST</H5></div>
      <div><h5>Download the <%= link_to("Student Agreement", "/downloads/student_agreement.pdf", :target => "_blank") %></h5></div>
      <div class="well col-md-5 ">
        <div><H3>Basic Grammar</H3></div>
        <br>
        <div>
          This class will focus on basic grammar and writing skills. We will begin with the fundamentals of sentence structure found in the the relationship between the subject and predicate.These fundamentals will be followed by lessons going over the various parts of speech and punctuation. The final week will be a recap of what we have learned with a focus on writing sentences. It is highly encouraged that students attend the full five weeks as each week will build on the next.
        </div>
      </div>
      <table id="lang" class="col-md-4 col-md-offset-1">
        <thead>
        <tr>
          <th id="scheduleWeek">Meeting</th>
          <th id="scheduleDate">Dates</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>1</td>
          <td>6/15 - 6/18</td>
        </tr>
        <tr>
          <td>2</td>
          <td>6/22 - 6/25</td>
        </tr>
        <tr>
          <td>3</td>
          <td>7/6 - 7/9</td>
        </tr>
        <tr>
          <td>4</td>
          <td>7/13 - 7/16</td>
        </tr>
        <tr>
          <td>5</td>
          <td>7/20 - 7/23</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/classes/2015/summer/lang/_grade_6.html.erb
<div id="schedulePanel" class="panel panel-default my-lang-panel">
  <div class="panel-heading" role="tab" id="heading6thGradeLang">
    <h4 class="panel-title">
      <a data-toggle="collapse"  href="#collapse6thGradeLang" aria-expanded="true" aria-controls="collapse6thGradeLang">
        6<sup>th</sup> / 7<sup>th</sup> / 8<sup>th</sup> Grade <i class="fa fa-plus-circle"></i>
      </a>
    </h4>
  </div>
  <div id="collapse6thGradeLang" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading6thGradeLang">
    <div class="panel-body">
      <div><H4>Instructor: <%= link_to("David Trius", team_path  + '#david-trius') %></H4></div>
      <div><H5>Day: Monday - Thursday</H5></div>
      <div><H5>Time: 5:30pm PST</H5></div>
      <div><h5>Download the <%= link_to("Student Agreement", "/downloads/student_agreement.pdf", :target => "_blank") %></h5></div>
      <div class="well col-md-5 ">
        <div><H3>Intermediate Writing</H3></div>
        <br>
        <div>
          This class will focus on writing skills for the middle school level. Each week will emphasize a different aspect of writing ending with a written assignment. Topics will include how to properly summarize, research, write a persuasive essay, figurative language, and analyzing poetry/literature. Certain topics will go hand in hand with one another so it is highly encouraged that students attend both weeks. These topics include research/writing a persuasive essay and figurative language/poetry.
        </div>
      </div>
      <table id="lang" class="col-md-4 col-md-offset-1">
        <thead>
        <tr>
          <th id="scheduleWeek">Meeting</th>
          <th id="scheduleDate">Dates</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>1</td>
          <td>6/15 - 6/18</td>
        </tr>
        <tr>
          <td>2</td>
          <td>6/22 - 6/25</td>
        </tr>
        <tr>
          <td>3</td>
          <td>7/6 - 7/9</td>
        </tr>
        <tr>
          <td>4</td>
          <td>7/13 - 7/16</td>
        </tr>
        <tr>
          <td>5</td>
          <td>7/20 - 7/23</td>
        </tr>
       </tbody>
      </table>
    </div>
  </div>
</div>